### PR TITLE
docs: translate hello world page

### PR DESCRIPTION
**Pull request by hardikpthv**
Translating **Hello World** page of the Docs section to Gujarati.

### CODE REVIEW

**Comment by hardikpthv** [comment]
@3sanket3 and @ron4ex, need your feedback on a few words, e.g. JavaScript is not translated into Gujarati જાવાસ્ક્રિપ્ટ. Just wondering which way do you think we should keep, for language or library names?

- રિએક્ટ or React
- જાવાસ્ક્રિપ્ટ or JavaScript

**Comment by ron4ex** [comment]
We should go with `React` and `JavaScript` rather than their Gujarati translations. This is because we want to preserve English words for APIs like `React.Component`. So let's just consider them as programming jargon and keep them as they are.

This also applies to other words like Node, DOM.

**Comment by hardikpthv** [comment]
Make sense. Thanks, @ron4ex, for the confirmation.

**Review by Chintan8860 — COMMENTED** [review]
Looking good

**Pull request merged**
